<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <?php echo $this->translate('Lista de Controladores') ?>
        </h1>
    </div>
</div>
<?php if(count($flashMessages)) {
    foreach ($flashMessages as $msg) { ?>
        <div class="alert alert-block alert-success">
            <a class="close" data-dismiss="alert" href="#">×</a>
            <p><?php echo $this->translate($msg) ?></p>
        </div>
    <?php }
} ?>
<p>
    <a class="btn btn-primary pull" href="<?php echo $this->url('acl-all/default', array('controller'=>'resource','action'=>'register')); ?>">
        <span class="glyphicon glyphicon-plus-sign"></span>&nbsp;Nuevo Controlador</a>
</p>
<br>
<div class="panel panel-default">
<div class="panel-body">
            <?php if (count($this->data) > 0 && !is_null($this->data)) { ?>
            <table class="table table-striped table-responsive table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th><?php echo $this->translate('Controlador') ?></th>
                        <th><?php echo $this->translate('Opciones') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->data as $entity): ?>
                    <tr>
                        <td><?php echo $entity->getId(); ?></td>
                        <td><?php echo $entity->getName(); ?></td>
                        <td class="text-center">
                            <a class="btn btn-xs btn-success" title="<?php echo $this->translate('Editar') ?>" href="<?php echo $this->url('acl-all/default', array('controller' => 'resource', 'action' => 'register', 'id' => $entity->getId())); ?>">
                                <span class="hidden-xs hidden-sm">
                                    <i class="fa fa-pencil-square-o"></i> <?php echo $this->translate('Editar') ?>
                                </span>
                                <span class="hidden-md hidden-lg"><i class="fa fa-pencil-square-o"></i></span>
                            </a>
                            <a class="btn btn-xs btn-danger" title="<?php echo $this->translate('Eliminar') ?>" href="<?php echo $this->url('acl-all/default', array('controller' => 'resource', 'action' => 'delete', 'id' => $entity->getId())); ?>">
                                <span class="hidden-xs hidden-sm">
                                    <i class="fa fa-trash-o"></i> <?php echo $this->translate('Eliminar') ?>
                                </span>
                                <span class="hidden-md hidden-lg"><i class="fa fa-trash-o"></i></span>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php if (count($this->data) > 1) { ?>
                <div class="text-center">
                    <?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>
                </div>
            <?php } ?>
            <?php } else { ?>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center"><strong><?php echo $this->translate('Resultados') ?></strong></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-center"><?php echo $this->translate('Ningun Resultado Encontrado') ?></td>
                    </tr>
                </tbody>
            </table>
            <?php } ?>
</div>
</div>
