<script type="text/javascript">
$(function() {
    // Validador Rut
    $("#username").Rut({
       on_error: function(){ alert('El rut ingresado es incorrecto'); }
   });
});
</script>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                <?php echo $this->translate('Usuarios') ?>
            </h1>
        </div>
    </div>

    <?php if(count($flashMessages)) {
        foreach ($flashMessages as $msg) { ?>
            <div class="alert alert-block alert-danger">
                <a class="close" data-dismiss="alert" href="#">×</a>
                <p><?php echo $this->translate($msg) ?></p>
            </div>
        <?php }
    } ?>
    <?php if(!empty($error)) : ?>
        <div class="alert alert-danger" role="alert">
            <?php foreach ($error as $otro) : ?>
                <?php foreach ($otro as $msgId => $msg) : ?>
                    <?php if($msgId != "notInArray"): ?>
                        <span class="glyphicon glyphicon-remove"></span>&nbsp;<?php echo $msg; ?><br/>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-users"></i> <?php echo ($this->id) ? $this->translate('Editar') : $this->translate('Nuevo Usuario') ; ?></h3>
                    </div>
                        <div class="panel-body">
                            <?php
                                $form = $this->form;
                                $form->setAttribute('action',$this->url('user-admin/default',array('action'=>'register','id'=>$this->id)));
                                $form->prepare();
                            ?>
                            <?php echo $this->form()->openTag($form); ?>
                            <?php $perfil = $form->get('perfil'); ?>
                            <?php echo $this->formHidden($form->get('id')); ?>
                            <?php echo $this->formHidden($perfil->get('id')); ?>
                            <div class="row">
                            <div class="col-md-6">
                              <div class="col-md-12">
                                    <div class="form-group">
                                        <label><?php echo $this->translate($this->formLabel($form->get('username'))); ?></label>
                                        <?php echo $this->formInput($form->get('username')); ?>
                                    </div>
                                    <div class="form-group">
                                        <label><?php echo $this->translate($this->formLabel($form->get('email'))); ?></label>
                                        <?php echo $this->formInput($form->get('email')); ?>
                                    </div>
                                    <div class="form-group">
                                        <label><?php echo $this->translate($this->formLabel($form->get('password'))); ?></label>
                                        <?php echo $this->formInput($form->get('password')); ?><div class="help-block with-errors"></div>
                                    </div>
                                    <div class="form-group">
                                        <label><?php echo $this->translate($this->formLabel($form->get('confirmation'))); ?></label>
                                        <?php echo $this->formInput($form->get('confirmation')); ?><div class="help-block with-errors"></div>
                                    </div>
                                    <div class="form-group">
                                        <label><?php echo $this->translate($this->formLabel($form->get('password_clue'))); ?></label>
                                        <?php echo $this->formInput($form->get('password_clue')); ?>
                                    </div>
                                    <div class="form-group" <?php if ($this->UserIdentity()->getRole()->getId() != 8) : echo "style='display:none;'"; endif;?>>
                                        <label><?php echo $this->translate($this->formLabel($form->get('role'))); ?></label>
                                        <?php echo $this->formSelect($form->get('role')); ?>
                                    </div>
                              </div>
                            </div>
                            <div class="col-md-6">
                              <div class="col-md-12">
                                    <div class="form-group">
                                        <label><?php echo $this->translate($this->formLabel($perfil->get('name'))); ?></label>
                                        <?php echo $this->formInput($perfil->get('name')); ?>
                                    </div>
                                    <div class="form-group">
                                        <label><?php echo $this->translate($this->formLabel($perfil->get('date_birth'))); ?></label>
                                        <?php echo $this->formInput($perfil->get('date_birth')); ?>
                                    </div>
                                    <div class="form-group">
                                        <label><?php echo $this->translate($this->formLabel($perfil->get('localization'))); ?></label>
                                        <?php echo $this->formInput($perfil->get('localization')); ?>
                                    </div>
                                    <div class="form-group" <?php if ($this->UserIdentity()->getRole()->getId() != 8) : echo "style='display:none;'"; endif;?>>
                                        <label><?php echo $this->translate($this->formLabel($perfil->get('obs'))); ?></label>
                                        <?php echo $this->formInput($perfil->get('obs')); ?>
                                    </div>
                                    <div class="form-group" <?php if ($this->UserIdentity()->getRole()->getId() != 8) : echo "style='display:none;'"; endif;?>>
                                        <label><?php echo $this->translate($this->formLabel($form->get('status'))); ?></label>
                                        <?php echo $this->formCheckbox($form->get('status')); ?>
                                    </div>
                                    <div class="form-group">
                                        <?php echo $this->formButton()->openTag($form->get('submit')); ?>
                                            <i class="fa fa-check"></i> <?php echo $this->translate($form->get('submit')->getValue()); ?>
                                        <?php echo $this->formButton()->closeTag(); ?>
                                    </div>
                              </div>
                            </div>
                            </div>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                </div>
            </div>
        </div>
   
