<script type="text/javascript">
$(function() {
    // Validador Rut
    $("#username").Rut({
       on_error: function(){ alert('El rut ingresado es incorrecto'); }
   });
});
</script>
<div class="row">

    <?php if(count($flashMessages)) {
        foreach ($flashMessages as $msg) { ?>
            <div class="alert alert-block alert-success">
                <a class="close" data-dismiss="alert" href="#">×</a>
                <p><?php echo $this->translate($msg) ?></p>
            </div>
        <?php }
    } ?>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Iniciar Sesión</h3>
                    </div>
                    <div class="panel-body">
                        <?php
                            $form = $this->form;
                            $form->setAttribute('action',$this->url('user-auth'));
                            $form->prepare();
                        ?>
                        <?php echo $this->form()->openTag($form); ?>
                            <fieldset>
                                <div class="form-group">
                                    <?php echo $this->formInput($form->get('username')); ?>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formInput($form->get('password')); ?>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <?php echo $this->formCheckbox($form->get('rememberme')); ?>
                                        <?php echo $this->formLabel($form->get('rememberme')); ?>
                                    </label>
                                </div>
                                <?php echo $this->formButton()->openTag($form->get('submit')); ?>
                                    <i class="fa fa-check"></i> <?php echo $this->translate($form->get('submit')->getValue()); ?>
                                <?php echo $this->formButton()->closeTag(); ?>
                                <?php echo $this->form()->closeTag(); ?>
                            </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
